// Shared types for every detection provider.

export interface DetectionResult {
  /** 0 = definitely human, 1 = definitely AI */
  score: number;
  label: 'human' | 'mixed' | 'ai' | 'na';
  /** Optional human-readable reason, used for the N/A case. */
  reason?: string;
}

/** Notes shorter than this (after cleanup) are skipped — too unreliable. */
export const MIN_TEXT_CHARS = 120;

export type DetectionMode = 'local' | 'api';

export interface ApiConfig {
  /** Base URL that exposes an OpenAI-compatible /chat/completions endpoint. */
  baseURL: string;
  /** Bearer token. Empty for local servers like Ollama / LM Studio. */
  apiKey: string;
  /** Model ID, e.g. "gpt-4o-mini", "claude-3-5-sonnet", "llama3.2". */
  model: string;
  /** Prompt describing how the model should score AI content. */
  systemPrompt: string;
  /** Request timeout in ms. */
  timeoutMs?: number;
}

export interface Settings {
  enabled: boolean;
  mode: DetectionMode;
  threshold: { mixed: number; ai: number };
  api: ApiConfig;
}

export interface Provider {
  /** Warm up (download model, validate key, etc.). Optional. */
  preload?(): void;
  detect(text: string): Promise<DetectionResult>;
}

export const DEFAULT_SYSTEM_PROMPT = `You are an AI-text-detection classifier.

Given a short piece of text, estimate the probability (0-100) that it was generated by a large language model such as GPT-4, Claude, or Gemini.

Consider: unnatural fluency, generic phrasing, AI-typical vocabulary (e.g. "delve", "leverage", "tapestry", "vibrant"), overly uniform sentence lengths, overuse of em dashes, structured paragraphs without a personal voice.

Output ONLY a single integer from 0 to 100. No explanation, no punctuation, no words.`;

export const PRESETS: Record<
  string,
  { label: string; baseURL: string; model: string; needsKey: boolean }
> = {
  openai: {
    label: 'OpenAI',
    baseURL: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini',
    needsKey: true,
  },
  openrouter: {
    label: 'OpenRouter',
    baseURL: 'https://openrouter.ai/api/v1',
    model: 'openai/gpt-4o-mini',
    needsKey: true,
  },
  deepseek: {
    label: 'DeepSeek',
    baseURL: 'https://api.deepseek.com/v1',
    model: 'deepseek-chat',
    needsKey: true,
  },
  ollama: {
    label: 'Ollama (localhost:11434)',
    baseURL: 'http://localhost:11434/v1',
    model: 'llama3.2',
    needsKey: false,
  },
  lmstudio: {
    label: 'LM Studio (localhost:1234)',
    baseURL: 'http://localhost:1234/v1',
    model: 'local-model',
    needsKey: false,
  },
  custom: {
    label: 'Custom',
    baseURL: '',
    model: '',
    needsKey: false,
  },
};

export const DEFAULT_SETTINGS: Settings = {
  enabled: true,
  mode: 'local',
  threshold: { mixed: 0.3, ai: 0.7 },
  api: {
    baseURL: PRESETS.openai.baseURL,
    apiKey: '',
    model: PRESETS.openai.model,
    systemPrompt: DEFAULT_SYSTEM_PROMPT,
    timeoutMs: 90000,
  },
};

export function scoreToLabel(
  score: number,
  threshold: Settings['threshold']
): DetectionResult['label'] {
  if (score >= threshold.ai) return 'ai';
  if (score >= threshold.mixed) return 'mixed';
  return 'human';
}
